l_simp_chinese:
 # Settings GUI
 DISCARD_DISABLED: "没有可弃用的修改"
 DISCARD_SETTINGS_TOOLTIP: "[SelectLocalization(JominiSettingsWindow.HasChanged, '', 'DISCARD_DISABLED')]"
 SAVECLOSE_SETTINGS_BUTTON: "[SelectLocalization(JominiSettingsWindow.HasChanged, 'SAVE_SETTINGS', 'CLOSE_SETTINGS')]"
 SAVE_SETTINGS: "保存"
 CLOSE_SETTINGS: "关闭"
 REQUIRE_SAVE_DESCRIPTION: "部分设置需要单击保存后才能生效"
 SETTINGS_CONFIRM_CHANGES: "你想要应用当前的修改吗？"
 APPLIES_ON_RESTART: "重启游戏后生效"
 APPLIES_ON_SAVE: "保存后生效"
 APPLIES_IMMEDIATLY: "立即生效"
 CHANGE_PROFILE_NAME: "更改个人资料名称"
 # General
 SETTING_VALUE_INT: "$VALUE|0$"
 # Graphics
 SETTING_TRIPLANAR_UV_QUALITY: "三维UV质量"
 SETTING_TRIPLANAR_UV_QUALITY_TOOLTIP: "#T $SETTING_TRIPLANAR_UV_QUALITY$#!\n影响陡峭地形表面的贴图质量。"
 OPTION_VERY_LOW: "极低"
 SETTING_UNIT_COA_RESOLUTION: "单位纹章分辨率"
 SETTING_UNIT_COA_RESOLUTION_TOOLTIP: "#T $SETTING_UNIT_COA_RESOLUTION$#!\n影响单位图形在制服上使用的纹章分辨率。"
 # System
 SETTING_EDITOR_TOOLTIP: "#T 编辑器#!用于打开游戏文件的文本编辑器"
 SETTING_HIDE_GAMECONTROLLER_CURSOR: "隐藏手柄光标"
 SETTING_HIDE_GAMECONTROLLER_CURSOR_TOOLTIP: "#T $SETTING_HIDE_GAMECONTROLLER_CURSOR$#!\n使用手柄而非鼠标时隐藏光标。"
 # Editor
 # Override
 CAMERA_TABLETOP: "桌面视角"
 # Audio Volume Settings
 SETTING_Master: "主设置"
 SETTING_Music: "     音乐"
 SETTING_UI: "     界面"
 SETTING_Ui_Clock: "          游戏速度时钟滴答声"
 SETTING_Effects: "     世界"
 SETTING_Ambient_Map: "          地图"
 SETTING_Armies: "               陆军和海军"
 SETTING_Ambient_Map_Background: "               地图环境背景"
 SETTING_Ambient_Objects: "环境地图对象"
 SETTING_Ambient_Panel: "环境插画"
 SETTING_Master_TOOLTIP: "#T 主音量\n#!设置游戏内所有音效的音量。"
 SETTING_Music_TOOLTIP: "#T 音乐音量\n#!设置游戏内所有音乐的音量。"
 SETTING_UI_TOOLTIP: "#T 界面音量\n#!设置用户界面音效的音量。"
 SETTING_Ui_Clock_TOOLTIP: "#T 游戏速度时钟滴答声\n#!设置在较高游戏速度下出现的游戏速度时钟指示器滴答声的音量。"
 SETTING_Effects_TOOLTIP: "#T 效果音量\n#!设置游戏世界中除音乐和界面音效外所有声音的音量。"
 SETTING_Ambient_Map_TOOLTIP: "#T 环境音量\n#!设置地图视图中所有声音的音量。"
 SETTING_Armies_TOOLTIP: "#T 陆军和海军音量\n#!设置地图上所有陆军和海军的音量。"
 SETTING_Ambient_Map_Background_TOOLTIP: "#T 环境音量\n#!设置地图上所有环境音效的音量。"
 SETTING_Ambient_Objects_TOOLTIP: "#T 地图物体环境音效\n#!设置地图上物体（如定居点和动物）发出的所有声音的音量。"
 SETTING_Ambient_Panel_TOOLTIP: "#T 插画环境音量\n#!设置所有与面板和插画相关的环境音效的音量。"
 # Audio Profiles Settings
 #SETTING_AUDIO_DEBUG_LOG_LEVEL: "Debug Log Level"
 SETTING_AUDIO_DEVICE_PROFILE: "音频配置"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!选择符合你的设备配置或聆听偏好（基于音频动态范围与混音效果）的音频配置文件。此设置不影响声道路由。"
 SETTING_AUDIO_OPTION_OFF: "关闭"
 SETTING_AUDIO_OPTION_OFF_TOOLTIP: "#T $SETTING_AUDIO_OPTION_OFF$\n#!默认混音采用完整动态范围。推荐大多数用户和扬声器配置使用此选项。"
 SETTING_AUDIO_OPTION_HOMECINEMA: "家庭影院"
 SETTING_AUDIO_OPTION_HOMECINEMA_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HOMECINEMA$\n#!$SETTING_AUDIO_OPTION_HOMECINEMA$的音频配置文件。可均衡动态范围并收紧低音，有助于使用低音炮的音响系统。"
 SETTING_AUDIO_OPTION_HEADPHONES: "耳机"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!$SETTING_AUDIO_OPTION_HEADPHONES$的音频配置方案。该方案能略微平衡动态范围，有助于削弱许多经典耳机设计中突出的频率。"
 SETTING_AUDIO_OPTION_SPEAKERS: "扬声器"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!外置$SETTING_AUDIO_OPTION_SPEAKERS$的音频配置文件。可增强特定频率，为没有低音炮的音响系统提供更饱满的音效。"
 SETTING_AUDIO_OPTION_TV: "电视"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!$SETTING_AUDIO_OPTION_TV$及小型扬声器的音频配置文件。可有效控制内置扬声器难以承载的低频，并增强高频清晰度。"
 SETTING_AUDIO_OPTION_NIGHTMODE: "夜间模式"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!适合夜间播放的柔和音频配置方案。该方案降低所有频率的动态范围，以便在较低音量下提高声音辨识度，并略微削减低音以减少干扰。"
 # Audio Music Settings
 SETTING_Music_Density: "音乐密度"
 SETTING_Music_Density_TOOLTIP: "#T 音乐密度调整\n#!设置音乐曲目间的间隔时长，范围从曲目间有较长间隔到几乎连续播放。默认值为20。"
 # Game
 SETTING_DEBUG_SAVES: "自动保存存档数量"
 SETTING_DEBUG_SAVES_TOOLTIP: "#T $SETTING_DEBUG_SAVES$#!\n保留的自动保存存档最大数量。"
 IRONMAN_BLOCKS_THIS: "@trigger_fail!铁人模式下不可用。"
 # Multiplayer
 SETTING_MAX_TICKS_AHEAD: "最大提前时数"
 SETTING_MAX_TICKS_AHEAD_TOOLTIP: "#T $SETTING_MAX_TICKS_AHEAD$#!\n为主机时，在等待客户端追赶前可提前运行的最大时数"
 # Override
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$#!\n设置多人游戏国家选择界面中存档文件传输的最大速度。\n\n较低设置可能提高加入多人游戏时的网络稳定性，但会延长多人游戏加载时间。"
 # Accessibility
 RELEVANT_HINTS: "相关提示"
 SETTING_HINTS: "提示"
 SETTING_SHOW_HINTS: "显示提示"
 SETTING_SHOW_HINTS_TOOLTIP: "#T 显示提示#!切换此选项以显示或隐藏提示"
 SETTING_LAST_HOST: "最后主机"
 SETTING_LAST_PLAYER: "最后玩家"
 SETTING_DIFFICULTY: "难度"
 SETTING_DISABLED_ALERTS: "屏蔽的警告"
 SETTING_CLOCK_TYPE: "时钟格式"
 SETTING_CLOCK_TYPE_TOOLTIP: "#T 时钟格式#!在12小时制和24小时制之间选择"
 CLOCK_TYPE_24H: "24小时制（如19:00）"
 CLOCK_TYPE_24H_SHORT: "24小时制"
 CLOCK_TYPE_12H: "12小时制（如7:00pm）"
 CLOCK_TYPE_12H_SHORT: "12小时制"
 CLOCK_TYPE_24H_SUFFIX: ":00"
 CLOCK_TYPE_24H_SHORT_SUFFIX: "h"
 CLOCK_TYPE_12H_SUFFIX_MORNING: ":00am"
 CLOCK_TYPE_12H_SUFFIX_AFTERNOON: ":00pm"
 CLOCK_TYPE_12H_SHORT_SUFFIX_MORNING: "am"
 CLOCK_TYPE_12H_SHORT_SUFFIX_AFTERNOON: "pm"
 AGENDA_SKIP_AGENDA_SETTING: "在游戏开始时不启用游戏推荐。"
 AGENDA_HISTORICAL_CONTEXT: "历史背景文本"
 AGENDA_WALKTHROUGH_DISABLED_MISSIONS: "@trigger_no!在任务树禁用状态下无法运行学习引导。请在主菜单的游戏规则中启用它们。"
 AGENDA_WALKTHROUGH_IS_RUNNING: "@trigger_no!学习引导已在进行中。"
 # Map
 SETTING_DRAW_TERRAIN: "绘制地形"
 SETTING_DRAW_WATER: "绘制水域"
 SETTING_DRAW_BORDERS: "绘制边界"
 SETTING_DRAW_TREES: "绘制树木"
 SETTING_DRAW_RIVERS: "绘制河流"
 SETTING_DRAW_POSTFX: "绘制后期特效"
 SETTING_DRAW_SKY: "绘制天空"
 SETTING_DRAW_BLOOM: "绘制泛光效果"
 SETTING_DRAW_TOOLTIPS: "绘制弹框提示"
 SETTING_DRAW_CITYSPRAWL: "绘制城市扩张模型"
 SETTING_DRAW_SHADOWS: "绘制阴影"
 SETTINGS_WEATHER_GRAPHIC_EFFECTS: "启用天气特效"
 SETTINGS_WEATHER_GRAPHIC_EFFECTS_TOOLTIP: "#T 启用天气特效 #! 切换天气效果以提升性能"
 SETTINGS_SINGLE_UNIT_ARMIES: "单个单位兵模"
 SETTINGS_SINGLE_UNIT_ARMIES_TOOLTIP: "#T 单个单位兵模#!地图上的军队兵模仅以单一兵模表现"
 SETTINGS_GRID_TILE_SIZE_TEXT: "城市模型大小"
 SETTINGS_GRID_TILE_SIZE_TEXT_TOOLTIP: "这项设置控制3D地图上城市建筑的尺寸大小。"
 # Categories
 SETTINGS_CATEGORY_INTERFACE: "界面设置"
 SETTINGS_CATEGORY_MULTIPLAYER: "多人游戏设置"
 SETTINGS_CATEGORY_MAP: "地图设置"
 SETTINGS_CATEGORY_COUNTRIES: "国家设置"
 SETTINGS_CATEGORY_TOOLTIPS: "弹框提示设置"
 SETTINGS_CATEGORY_CONFIRM: "确认模式设置"
 SETTINGS_CATEGORY_INPUT_LOCK: "输入锁定设置"
 SETTINGS_CATEGORY_DYNAMIC_NAMES: "动态国名"
 SETTINGS_CATEGORY_PLAYSETS: "Playsets"
 # Hotkeys
 SETTING_INPUT_CONTEXT_COMMON: "通用快捷键"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "#T 通用 #! 最常用的按键绑定"
 SETTING_INPUT_CONTEXT_WINDOW_TAB: "窗口快捷键"
 SETTING_INPUT_CONTEXT_WINDOW_TAB_TOOLTIP: "#T 窗口 #! 用于窗口和标签页的按键绑定"
 SETTING_INPUT_CONTEXT_MAP: "地图快捷键"
 SETTING_INPUT_CONTEXT_MAP_TOOLTIP: "#T 地图 #! 地图操作相关按键绑定"
 SETTING_INPUT_CONTEXT_MAP_MODE: "地图模式快捷键"
 SETTING_INPUT_CONTEXT_MAP_MODE_TOOLTIP: "#T 地图模式 #! 切换地图模式的按键绑定"
 SETTING_INPUT_CONTEXT_PAUSE_MENU: "暂停菜单快捷键"
 SETTING_INPUT_CONTEXT_PAUSE_MENU_TOOLTIP: "#T 暂停菜单 #! 暂停菜单相关按键绑定"
 SETTING_INPUT_ACTION_CLOSE: "关闭"
 SETTING_INPUT_ACTION_CLOSE_LEFT: "关闭左侧面板"
 SETTING_INPUT_ACTION_CLOSE_RIGHT: "关闭右侧面板"
 SETTING_INPUT_ACTION_CONFIRM: "确认"
 SETTING_INPUT_ACTION_TOGGLE_PAUSE: "切换暂停"
 SETTING_INPUT_ACTION_PAUSE: "暂停"
 SETTING_INPUT_ACTION_UNPAUSE: "取消暂停"
 SETTING_INPUT_ACTION_RESUME: "继续"
 SETTING_INPUT_ACTION_REPORT_ISSUE: "报告问题"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "加速"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "减速"
 SETTING_INPUT_ACTION_SPEED_ONE: "速度1"
 SETTING_INPUT_ACTION_SPEED_TWO: "速度2"
 SETTING_INPUT_ACTION_SPEED_THREE: "速度3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "速度4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "速度5"
 SETTING_INPUT_ACTION_SHOW_MENU: "显示菜单"
 SETTING_INPUT_ACTION_CAMERA_UP: "镜头上移"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "镜头下移"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "镜头左移"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "镜头右移"
 SETTING_INPUT_ACTION_CAMERA_ZOOM_IN: "镜头拉近"
 SETTING_INPUT_ACTION_CAMERA_ZOOM_OUT: "镜头拉远"
 SETTING_INPUT_ACTION_CAMERA_DRAG: "拖拽镜头"
 SETTING_INPUT_ACTION_CAMERA_ROTATE: "旋转镜头"
 SETTING_INPUT_ACTION_SAVE: "保存"
 SETTING_INPUT_ACTION_LOAD: "加载"
 SETTING_INPUT_ACTION_GO_TO_CAPITAL: "转到首都"
 SETTING_INPUT_ACTION_FIND_PROVINCE: "查找省份"
 SETTING_INPUT_ACTION_CONSOLIDATE: "整编部队"
 SETTING_INPUT_ACTION_DETACH_SIEGE: "分离围攻部队"
 SETTING_INPUT_ACTION_DETACH_DAMAGED_SHIP: "分离受损船只"
 SETTING_INPUT_ACTION_SPLIT_HALF: "平分单位"
 SETTING_INPUT_ACTION_REORG_UNITS: "重整单位"
 SETTING_INPUT_ACTION_MERGE_UNITS: "合并单位"
 SETTING_INPUT_ACTION_PREVIOUS_WINDOW: "上一个窗口"
 SETTING_INPUT_ACTION_PREVIOUS_WINDOW_LEFT: "左侧上一个窗口"
 SETTING_INPUT_ACTION_PREVIOUS_WINDOW_RIGHT: "右侧上一个窗口"
 SETTING_INPUT_ACTION_NEXT_WINDOW: "下一个窗口"
 SETTING_INPUT_ACTION_NEXT_WINDOW_LEFT: "左侧下一个窗口"
 SETTING_INPUT_ACTION_NEXT_WINDOW_RIGHT: "右侧下一个窗口"
 SETTING_INPUT_ACTION_MACRO_BUILDER: "总建造器"
 SETTING_INPUT_ACTION_SCREENSHOT: "截图"
 SETTING_INPUT_ACTION_SCREENSHOT_MAP: "地图截图"
 SETTING_INPUT_ACTION_MAX_ZOOM_OUT: "最大缩放"
 SETTING_INPUT_ACTION_DELETE: "删除"
 SETTING_INPUT_ACTION_GUI_DEBUG: "界面调试"
 SETTING_INPUT_ACTION_OPEN_UNIT_VIEWER_ON_UNIT: "在选中单位上打开单位查看器"
 SETTING_INPUT_ACTION_ALLOW_ATTACH: "允许跟随"
 SETTING_INPUT_ACTION_ATTACH_TO_UNIT: "跟随该单位"
 SETTING_INPUT_ACTION_CREATE_NEW_UNIT: "创建新单位"
 SETTING_INPUT_ACTION_DETACH_SUPPORT: "分离辅助部队"
 SETTING_INPUT_ACTION_DISBAND: "解散"
 SETTING_INPUT_ACTION_DO_SHATTERED_RETREAT: "下令溃退"
 SETTING_INPUT_ACTION_EMBARK: "登船"
 SETTING_INPUT_ACTION_RECRUIT_TO: "招募至"
 SETTING_INPUT_ACTION_SELECT_OBJECTIVE: "选择目标"
 SETTING_INPUT_ACTION_CONSOLE: "控制台"
 SETTING_INPUT_ACTION_DISABLE_GUI: "禁用图形界面"
 SETTING_INPUT_ACTION_LOCK_CAMERA: "锁定镜头"
 SETTING_INPUT_ACTION_TOP_LEFT_1: "政府面板"
 SETTING_INPUT_ACTION_TOP_LEFT_2: "经济面板"
 SETTING_INPUT_ACTION_TOP_LEFT_3: "生产面板"
 SETTING_INPUT_ACTION_TOP_LEFT_4: "社会面板"
 SETTING_INPUT_ACTION_TOP_LEFT_5: "外交面板"
 SETTING_INPUT_ACTION_TOP_LEFT_6: "军事面板"
 SETTING_INPUT_ACTION_TOP_LEFT_7: "地理面板"
 SETTING_INPUT_ACTION_TOP_LEFT_8: "革新面板"
 SETTING_INPUT_ACTION_TOP_LEFT_9: "左上9号键"
 SETTING_INPUT_ACTION_TOP_LEFT_10: "左上10号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_1: "右上1号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_2: "右上2号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_3: "右上3号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_4: "右上4号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_5: "右上5号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_6: "右上6号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_7: "右上7号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_8: "右上8号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_9: "右上9号键"
 SETTING_INPUT_ACTION_TOP_RIGHT_10: "右上10号键"
 SETTING_INPUT_ACTION_CONTROL_GROUP_0: "Control Group 0"
 SETTING_INPUT_ACTION_CONTROL_GROUP_1: "Control Group 1"
 SETTING_INPUT_ACTION_CONTROL_GROUP_2: "Control Group 2"
 SETTING_INPUT_ACTION_CONTROL_GROUP_3: "Control Group 3"
 SETTING_INPUT_ACTION_CONTROL_GROUP_4: "Control Group 4"
 SETTING_INPUT_ACTION_CONTROL_GROUP_5: "Control Group 5"
 SETTING_INPUT_ACTION_CONTROL_GROUP_6: "Control Group 6"
 SETTING_INPUT_ACTION_CONTROL_GROUP_7: "Control Group 7"
 SETTING_INPUT_ACTION_CONTROL_GROUP_8: "Control Group 8"
 SETTING_INPUT_ACTION_CONTROL_GROUP_9: "Control Group 9"
 SETTING_INPUT_ACTION_MAPMODE_MENU: "切换地图模式菜单"
 # Tooltips
 SETTING_TOOLTIP_MODE: "弹框提示模式"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\n设置弹窗提示框的锁定方式。"
 SETTING_TOOLTIP_MODE_NO_LOCK: "无锁定"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "鼠标倾向模式"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "操作锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "计时锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "操作锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "计时锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "计时或操作锁定"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\n设置弹窗提示框显示前的延迟时间。"
 SETTING_TOOLTIP_DELAY: "显示延迟"
 SETTING_TOOLTIP_UNLOCK_TIME: "解锁延迟"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n设置弹窗提示框解锁显示前的延迟时间。"
 SETTING_TOOLTIP_LOCK_TIME: "锁定延迟"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n设置弹窗提示框前锁定的延迟时间。"
 SETTING_TOOLTIP_SHOW_EXTRA_INFO_DELAY_TIME: "额外信息显示延迟"
 SETTING_TOOLTIP_SHOW_EXTRA_INFO_DELAY_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_SHOW_EXTRA_INFO_DELAY_TIME$#!\n设置显示额外信息前的延迟时间。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "锁定状态开启延迟"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n设置已打开另一弹框提示时，弹框提示锁定之前的延时。"
 #Map tooltips
 SETTING_MAP_TOOLTIPS_ENABLE: "地图弹框提示"
 SETTING_MAP_TOOLTIPS_ENABLE_TOOLTIP: "#T $SETTING_MAP_TOOLTIPS_ENABLE$#!\n启用鼠标悬停地图时显示弹框提示功能"
 SETTING_MAP_TOOLTIPS_DELAY: "地图弹框提示延迟"
 SETTING_MAP_TOOLTIPS_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIPS_DELAY$#!\n光标静止后显示地图弹框提示所需时间"
 SETTING_MAP_TOOLTIPS_ENABLE_DISABLED: "禁用"
 SETTING_MAP_TOOLTIPS_ENABLE_NO_SEAZONES: "没有海域"
 SETTING_MAP_TOOLTIPS_ENABLE_ENABLED: "启用"
 #Player Proficiency
 SETTING_PLAYER_PROFICIENCY: "玩家熟练度"
 SETTING_PLAYER_PROFICIENCY_TOOLTIP: "#T $SETTING_PLAYER_PROFICIENCY$#!\n决定游戏中将获得多少辅助功能。"
 SETTING_PLAYER_PROFICIENCY_UNKNOWN: "未设置"
 SETTING_PLAYER_PROFICIENCY_NOVICE: "新手"
 SETTING_PLAYER_PROFICIENCY_EXPERIENCED: "老手"
 SETTING_PLAYER_PROFICIENCY_ADVANCED: "进阶"
 SETTING_PLAYER_PROFICIENCY_EXPERT: "专家"
 SETTING_SKIP_WELCOME_NEW_GAME: "跳过新游戏欢迎窗口"
 SETTING_SKIP_WELCOME_NEW_GAME_TOOLTIP: "#T $SETTING_SKIP_WELCOME_NEW_GAME$#!\n$SETTING_SKIP_WELCOME_NEW_GAME_POPUP$"
 SETTING_SKIP_WELCOME_NEW_GAME_POPUP: "不再显示欢迎窗口，而是直接打开世界地图。"
 #MP Chat Position
 SETTING_MP_CHAT_POSITION: "游戏内多人聊天位置"
 SETTING_MP_CHAT_POSITION_LOBBY: "国家选择界面多人聊天位置"
 # Confirm
 SETTING_CONFIRM_MODE: "确认模式"
 SETTING_CONFIRM_MODE_HOLD: "长按确认"
 SETTING_CONFIRM_MODE_DIALOG: "对话框确认"
 SETTING_CONFIRM_MODE_TOOLTIP: "#T $SETTING_CONFIRM_MODE$#!\n设置操作确认方式。"
 #Dismiss
 SETTING_EVENT_WINDOW_INPUT_LOCK_TIME: "事件窗口输入锁定"
 SETTING_EVENT_WINDOW_INPUT_LOCK_TIME_TOOLTIP: "#T $SETTING_EVENT_WINDOW_INPUT_LOCK_TIME$#!\n在弹出窗口中锁定按钮一段时间。"
 SETTING_POPUP_MESSAGE_INPUT_LOCK_TIME: "弹出消息输入锁定"
 SETTING_POPUP_MESSAGE_INPUT_LOCK_TIME_TOOLTIP: "#T $SETTING_POPUP_MESSAGE_INPUT_LOCK_TIME$#!\n在弹出窗口中锁定按钮一段时间。"
 #Graphics
 SETTING_SSR_QUALITY: "反射效果"
 SETTING_SSR_QUALITY_TOOLTIP: "#T $SETTING_SSR_QUALITY$#!\n降低质量可提高帧率。"
 SETTING_BLUR_QUALITY: "界面模糊质量"
 SETTING_BLUR_QUALITY_TOOLTIP: "#T $SETTING_BLUR_QUALITY$#!\n影响部分界面视图对背景应用的模糊效果。降低质量可提升低端或集成显卡的帧率。"
 SETTING_FLATMAP_MODE: "平面地图模式"
 SETTING_FLATMAP_MODE_TOOLTIP: "#T $SETTING_FLATMAP_MODE$#!\n设置平面地图的显示时机。"
 SETTING_FLATMAP_MODE_ZOOMED_OUT: "缩小时显示"
 SETTING_FLATMAP_MODE_IN_FOG_OF_WAR: "缩小时或战争迷雾中显示"
 SETTING_FLATMAP_MODE_FOG_OF_WAR_IGNORE_ZOOM: "仅战争迷雾中显示"
 SETTING_FLATMAP_MODE_ALWAYS: "始终显示"
 SETTING_FLATMAP_MODE_NEVER: "从不显示"
 SETTING_MAXIMIZE_TICK_SPEED: "最大化刻速"
 SETTING_MAXIMIZE_TICK_SPEED_TOOLTIP: "#T $SETTING_MAXIMIZE_TICK_SPEED$#!\n在游戏速度达到最高时，优先将CPU用于刻速，而不是保持平滑的帧率。启用后，速度4将表现为禁用时的速度5。"
 SETTING_DISABLE_3D_TERRAIN: "禁用3D地形"
 SETTING_DISABLE_3D_TERRAIN_TOOLTIP: "#T $SETTING_DISABLE_3D_TERRAIN$#!\n禁用3D地形加载以提高性能。"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN: "填充不可通行地形"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_RESET$#!\n决定地图上是否将不可通行地形包含在国家边界内。"
 SETTING_CAMERA_ROTATION_RESET: "镜头旋转重置"
 SETTING_CAMERA_ROTATION_RESET_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_RESET$#!\n决定用户旋转镜头后是否自动重置为默认位置。"
 SETTING_FLATMAP_WATER_COLOR: "平面地图水域颜色"
 SETTING_FLATMAP_WATER_COLOR_TOOLTIP: "#T $SETTING_FLATMAP_WATER_COLOR$#!\n决定平面地图中用于表示水域的颜色。"
 SETTING_BLUE_WATER: "蓝色"
 SETTING_BROWN_WATER: "棕色"
 SETTING_PROVINCE_NAMES: "省份名称显示"
 SETTING_PROVINCE_NAMES_TOOLTIP: "#T $SETTING_PROVINCE_NAMES$#!\n决定城市和省份名称在地图上的显示方式。"
 MAPNAME_MODE_MOUSE_OVER: "鼠标悬停时显示"
 MAPNAME_MODE_ALWAYS_ON: "始终显示"
 MAPNAME_MODE_ALWAYS_OFF: "始终隐藏"
 SETTING_SUBJECTS_USE_OVERLORD_NAME: "附属国显示宗主国名称"
 SETTING_SUBJECTS_USE_OVERLORD_NAME_TOOLTIP: "#T $SETTING_SUBJECTS_USE_OVERLORD_NAME$#!\n决定缩小时政治地图上附属国是否显示其宗主国名称。"
 SETTING_SUBJECTS_USE_OVERLORD_NAME_NO: "否"
 SETTING_SUBJECTS_USE_OVERLORD_NAME_YES: "是（默认）"
 SETTING_SUBJECTS_USE_OVERLORD_COLOR: "附属国使用宗主国颜色"
 SETTING_SUBJECTS_USE_OVERLORD_COLOR_TOOLTIP: "#T $SETTING_SUBJECTS_USE_OVERLORD_COLOR$#!\n决定政治地图上附属国如何显示其宗主国颜色。"
 SETTING_SUBJECTS_USE_OVERLORD_COLOR_NO: "否"
 SETTING_SUBJECTS_USE_OVERLORD_COLOR_BLEND: "混合(默认)"
 SETTING_SUBJECTS_USE_OVERLORD_COLOR_YES: "是"
 SETTING_COUNTRY_NAMES: "国家名称显示"
 SETTING_COUNTRY_NAMES_TOOLTIP: "#T $SETTING_COUNTRY_NAMES$#!\n决定地图上显示的国家名称是始终简短（如英格兰）、完整（如英格兰王国），还是根据国家大小动态变化。"
 SETTING_COUNTRY_NAMES_SHORT: "始终简短"
 SETTING_COUNTRY_NAMES_DYNAMIC: "动态变化（默认）"
 SETTING_COUNTRY_NAMES_LONG: "始终完整"
 SETTING_IO_SHOW_AS_OVERLORDS: "国际组织显示为宗主国"
 SETTING_IO_SHOW_AS_OVERLORDS_TOOLTIP: "#T $SETTING_IO_SHOW_AS_OVERLORDS$#!\n决定某些国际组织（如神圣罗马帝国）是否在政治地图上显示为宗主国。"
 SETTING_IO_SHOW_AS_OVERLORDS_NO: "否(默认)"
 SETTING_IO_SHOW_AS_OVERLORDS_YES: "是"
 SETTING_LOCATION_NAME_LANGUAGE: "动态地名"
 SETTING_LOCATION_NAME_LANGUAGE_TOOLTIP: "#T $SETTING_LOCATION_NAME_LANGUAGE$#!\n决定文化语言是否影响地点动态名称。\n\n$SETTING_LOCATION_NAME_LANGUAGE_COMMON$：地点将使用所属国主流文化的语言命名。\n\n$SETTING_LOCATION_NAME_LANGUAGE_DOMINANT$：地点将使用当地人口中占主导地位的文化语言命名。\n\n$SETTING_LOCATION_NAME_LANGUAGE_UNTRANSLATED$：地点名称始终使用默认名称。"
 SETTING_LOCATION_NAME_LANGUAGE_COMMON: "所属国语言（默认）"
 SETTING_LOCATION_NAME_LANGUAGE_DOMINANT: "人口语言"
 SETTING_LOCATION_NAME_LANGUAGE_UNTRANSLATED: "无动态地名"
 SETTING_ESTATES_NAME_LANGUAGE: "动态阶层名称"
 SETTING_ESTATES_NAME_LANGUAGE_TOOLTIP: "#T $SETTING_ESTATES_NAME_LANGUAGE$#!\n决定文化语言是否影响阶层名称。\n\n$SETTING_ESTATES_NAME_LANGUAGE_COMMON$：阶层将使用国家主流文化的语言命名。\n\n$SETTING_ESTATES_NAME_LANGUAGE_UNTRANSLATED$：阶层名称始终使用基础名称。"
 SETTING_ESTATES_NAME_LANGUAGE_COMMON: "所属国语言（默认）"
 SETTING_ESTATES_NAME_LANGUAGE_UNTRANSLATED: "无动态阶层名"
 SETTING_PARLIAMENT_NAME_LANGUAGE: "动态议会名称"
 SETTING_PARLIAMENT_NAME_LANGUAGE_TOOLTIP: "#T $SETTING_PARLIAMENT_NAME_LANGUAGE$#!\n决定文化语言是否影响议会名称。\n\n$SETTING_PARLIAMENT_NAME_LANGUAGE_COMMON$：议会将使用国家主流文化的语言命名。\n\n$SETTING_PARLIAMENT_NAME_LANGUAGE_UNTRANSLATED$：议会名称始终使用基础名称。"
 SETTING_PARLIAMENT_NAME_LANGUAGE_COMMON: "所属国语言（默认）"
 SETTING_PARLIAMENT_NAME_LANGUAGE_UNTRANSLATED: "无动态议会名"
 SETTING_LOW_QUALITY_SHADERS: "低质量着色器"
 SETTING_LOW_QUALITY_SHADERS_TOOLTIP: "#T $SETTING_LOW_QUALITY_SHADERS$#!\n牺牲部分画质以提升性能。\n此设置会显著影响视觉效果，但性能提升主要在使用低端GPU或集成显卡的系统上较为明显。"
 SETTING_MONTHLY_AUTOPAUSE: "每月自动暂停"
 SETTING_MONTHLY_AUTOPAUSE_TOOLTIP: "#T $SETTING_MONTHLY_AUTOPAUSE$#!\n每月开始时自动暂停游戏。"
 SETTING_GAME_SPEED_ON_WAR: "战争开始时的游戏速度"
 SETTING_GAME_SPEED_ON_WAR_TOOLTIP: "#T $SETTING_GAME_SPEED_ON_WAR$#!\n设置我国进入战争时游戏速度的变化。"
 SETTING_GAME_SPEED_ON_WAR_LEAVE: "保持不变"
 SETTING_GAME_SPEED_ON_WAR_1: "最低速"
 SETTING_GAME_SPEED_ON_WAR_2: "低速"
 SETTING_GAME_SPEED_ON_WAR_3: "中速"
 SETTING_GAME_SPEED_ON_WAR_4: "高速"
 SETTING_GAME_SPEED_ON_WAR_5: "最高速"
 SETTING_GAME_SPEED_ON_UNIT_SELECT: "选中单位进入战斗时的游戏速度"
 SETTING_GAME_SPEED_ON_UNIT_SELECT_TOOLTIP: "#T $SETTING_GAME_SPEED_ON_UNIT_SELECT$#!\n设置选中单位进入战斗时游戏速度的变化。"
 SETTING_ENABLE_PARTICLES: "启用粒子效果"
 SETTING_ENABLE_PARTICLES_TOOLTIP: "#T $SETTING_ENABLE_PARTICLES$#!\n允许禁用游戏中的粒子效果以提高性能。"
 SETTING_GUI_TEXTURE_STREAMING: "GUI纹理流式加载"
 SETTING_GUI_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_GUI_TEXTURE_STREAMING$\n#!切换图形用户界面元素的流式传输\n启用此选项将降低显存占用，但可能导致暂时性的画质下降。"
 #Playsets
 SETTINGS_WARNING_PLAYSET: "Show dialog to warn about playset errors"
